export const WORDLIST = [
  'anchor', 'apple', 'amber', 'arrow', 'atlas', 'autumn', 'alpha', 'acorn',
  'bacon', 'badge', 'baker', 'banjo', 'basil', 'beach', 'bison', 'bloom',
  'brave', 'bread', 'brick', 'bridge', 'bronze', 'brush', 'bubble', 'bundle',
  'cabin', 'cable', 'cactus', 'camera', 'candle', 'canyon', 'carbon', 'cargo',
  'carrot', 'castle', 'cedar', 'cello', 'chain', 'chalk', 'charm', 'cherry',
  'chess', 'cider', 'cliff', 'cloud', 'clover', 'cobalt', 'cocoa', 'comet',
  'copper', 'coral', 'cotton', 'cradle', 'crane', 'crayon', 'cream', 'creek',
  'crown', 'crystal', 'cube', 'curry', 'cycle', 'daisy', 'dance', 'dawn',
  'delta', 'denim', 'desert', 'diamond', 'diesel', 'dolphin', 'domino', 'donut',
  'dragon', 'dream', 'drift', 'drum', 'dusk', 'eagle', 'earth', 'easel',
  'echo', 'ember', 'engine', 'epoch', 'equal', 'ether', 'expert', 'fable',
  'falcon', 'fancy', 'feather', 'fern', 'fiber', 'fiddle', 'field', 'fig',
  'flame', 'flask', 'flint', 'float', 'flute', 'forest', 'fossil', 'fox',
  'frost', 'fuel', 'fudge', 'garden', 'garlic', 'gecko', 'gem', 'ginger',
  'glacier', 'glass', 'globe', 'glow', 'gold', 'granite', 'grape', 'gravel',
  'green', 'grove', 'guitar', 'gulf', 'hammer', 'harbor', 'harvest', 'hazel',
  'heron', 'hive', 'honey', 'horizon', 'hotel', 'ice', 'indigo', 'ink',
  'iris', 'iron', 'island', 'ivory', 'jade', 'jazz', 'jelly', 'jet',
  'jungle', 'juniper', 'kayak', 'kettle', 'kite', 'koala', 'lagoon', 'lamp',
  'lantern', 'laser', 'laurel', 'lava', 'leaf', 'ledger', 'lemon', 'lens',
  'lily', 'linen', 'lion', 'lobby', 'lotus', 'lunar', 'lynx', 'magnet',
  'mango', 'maple', 'marble', 'marsh', 'meadow', 'melon', 'mercy', 'meteor',
  'mint', 'mirror', 'moss', 'motor', 'muffin', 'nectar', 'needle', 'nest',
  'nickel', 'ninja', 'noble', 'north', 'nova', 'oak', 'oasis', 'ocean',
  'olive', 'onyx', 'opal', 'orbit', 'orchid', 'otter', 'oxide', 'oyster',
  'paddle', 'palm', 'panda', 'paper', 'parrot', 'pastel', 'peach', 'pearl',
  'pebble', 'pencil', 'penguin', 'pepper', 'petal', 'piano', 'pigeon', 'pilot',
  'pine', 'pixel', 'planet', 'plaza', 'plum', 'polar', 'pollen', 'poppy',
  'prism', 'puma', 'quartz', 'quest', 'quill', 'rabbit', 'radar', 'raft',
  'rain', 'raven', 'ribbon', 'ridge', 'river', 'robin', 'rocket', 'rose',
  'ruby', 'saddle', 'sage', 'salmon', 'sand', 'sapphire', 'satin', 'scout',
  'shadow', 'shell', 'silk', 'silver', 'sky', 'slate', 'smoke', 'snow',
] as const

export const WORDLIST_BITS = Math.log2(WORDLIST.length)
