/** Extract HugeIcons into src/lib/hugeicons.ts. Run: npm run icons */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const ICONS = [
  'activity-01',
  'alert-02',
  'alert-circle',
  'arrow-down-01',
  'arrow-left-01',
  'arrow-right-01',
  'arrow-up-01',
  'cancel-circle',
  'checkmark-circle-02',
  'clock-01',
  'cloud',
  'code',
  'copy-01',
  'dashboard-speed-01',
  'dice',
  'earth',
  'file-export',
  'github',
  'global-search',
  'information-circle',
  'key-01',
  'link-02',
  'loading-03',
  'location-01',
  'minus-sign',
  'moon-02',
  'plus-sign',
  'refresh',
  'search-01',
  'security-check',
  'server-stack-01',
  'shield-01',
  'square-lock-01',
  'sun-03',
  'text-font',
  'tick-02',
  'wifi-01',
];

const setPath = require.resolve('@iconify-json/hugeicons/icons.json');
const set = JSON.parse(readFileSync(setPath, 'utf8'));

const missing = ICONS.filter((name) => !set.icons[name]);
if (missing.length) {
  console.error(`Unknown HugeIcons names: ${missing.join(', ')}`);
  process.exit(1);
}

const width = set.width ?? 24;
const height = set.height ?? 24;

const entries = ICONS.map((name) => {
  const icon = set.icons[name];
  const body = icon.body.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  return `  '${name}': { body: '${body}', width: ${icon.width ?? width}, height: ${icon.height ?? height} },`;
}).join('\n');

const out = `// GENERATED by scripts/generate-icons.mjs, do not edit by hand.
// Source: @iconify-json/hugeicons v${set.info?.version ?? 'unknown'}

export type IconData = { body: string; width: number; height: number };

export const HUGEICONS = {
${entries}
} as const satisfies Record<string, IconData>;

export type IconName = keyof typeof HUGEICONS;
`;

mkdirSync(join(root, 'src/lib'), { recursive: true });
writeFileSync(join(root, 'src/lib/hugeicons.ts'), out, 'utf8');
console.log(`Wrote src/lib/hugeicons.ts with ${ICONS.length} icons.`);
