/** Copy flag-icons SVGs into public/flags/. Run: npm run flags */
import {
  copyFileSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const manifest = require.resolve('flag-icons/package.json');
const pkg = JSON.parse(readFileSync(manifest, 'utf8'));
const source = join(dirname(manifest), 'flags/4x3');
const target = join(root, 'public/flags');

rmSync(target, { recursive: true, force: true });
mkdirSync(target, { recursive: true });

const codes = [];
for (const file of readdirSync(source)) {
  if (!file.endsWith('.svg')) continue;
  copyFileSync(join(source, file), join(target, file));
  codes.push(file.slice(0, -4));
}

codes.sort();

const out = `// GENERATED by scripts/generate-flags.mjs, do not edit by hand.
// Source: flag-icons v${pkg.version} - the SVGs live in public/flags/.

export const FLAG_CODES: ReadonlySet<string> = new Set([
${codes.map((code) => `  '${code}',`).join('\n')}
]);
`;

mkdirSync(join(root, 'src/lib'), { recursive: true });
writeFileSync(join(root, 'src/lib/flags.ts'), out, 'utf8');
console.log(`Copied ${codes.length} flags to public/flags and wrote src/lib/flags.ts.`);
